#!/usr/bin/env ruby

require 'fileutils'

xmonad_dots = %w(
  .Xmodmap
  .Xdefaults
  .xmonad
  .xinitrc
)

obsolete_dots = %w(
  .bashrc
)

dots = %w(
  .vimrc
  .gvimrc
  .vim
  .irbrc
  .gitconfig
  .tmux.conf
  bin
  .emacs.d
  .zsh
  .zshrc
  .zshenv
)

FileUtils.mkdir_p 'dotfiles/old'

dots.each do |dot|
  if File.exist?(dot) && File.stat(dot).ino != File.stat("dotfiles/#{dot}").ino
    puts "mv #{dot} dotfiles/old/#{dot}"
    FileUtils.mv(dot, "dotfiles/old/#{dot}")
    puts "ln -s dotfiles/#{dot} #{dot}"
    FileUtils.ln("dotfiles/#{dot}", dot)
  end

  unless File.exist?(dot)
    puts "ln -s dotfiles/#{dot} #{dot}"
    FileUtils.ln("dotfiles/#{dot}", dot)
  end
end

