#!/bin/sh
mv .vimrc .vimrc.old && ln -sf dotfiles/.vimrc .vimrc
mv .vim .vim.old && ln -sf dotfiles/.vim .vim
mv .bashrc .bashrc.old && ln -sf dotfiles/.bashrc
mv .xmonad .xmonad.old && ln -sf .xmonad .
