#!/bin/sh
mv .vimrc .vimrc.old ; ln -sf dotfiles/.vimrc .vimrc
mv .gvimrc .gvimrc.old ; ln -sf dotfiles/.gvimrc .gvimrc
mv .vim .vim.old ; ln -sf dotfiles/.vim .vim
mv .xinitrc .xinitrc.old ; ln -sf dotfiles/.xinitrc .xinitrc
mv .vimperatorrc .vimperatorrc.old ; ln -sf dotfiles/.vimperatorrc .vimperatorrc
mv .vimperator .vimperator.old ; ln -sf dotfiles/.vimperator .vimperator
mv .irbrc .irbrc.old ; ln -sf dotfiles/.irbrc .irbrc
mv .bashrc .bashrc.old ; ln -sf dotfiles/.bashrc
mv .Xmodmap .Xmodmap.old ; ln -sf dotfiles/.Xmodmap
mv .Xdefaults .Xdefaults.old ; ln -sf dotfiles/.Xdefaults
mv .xmonad .xmonad.old ; ln -sf dotfiles/.xmonad .xmonad
mv .gitconfig .gitconfig.old ; ln -sf dotfiles/.gitconfig .gitconfig
mv bin bin.old; ln -sf dotfiles/bin bin
