#! perl -w

# David Turnbull <dsturnbull@gmail.com>
# intermediate buffer to store primary X11 selection.

# Usage: put in your .Xdefaults the following lines
# URxvt.perl-ext-common: x11-clipboard
# URxvt.keysym.M-v: perl:x11-clipboard:paste

use Fcntl ();
use locale;
use utf8;

sub on_sel_grab {
  open CLIPBOARD, ">/tmp/intermediate_buffer";
  print CLIPBOARD $_[0]->selection;
  close CLIPBOARD;
  open PB, "| pbcopy";
  print PB $_[0]->selection;
  close PB;
  ()
}

sub paste {
  my ($str, $data);

  $str = `/Users/dave/.urxvt/x11-clipboard-contents`;
  if ($str eq "") {
    open CLIPBOARD, "/tmp/intermediate_buffer";
    while ((read CLIPBOARD, $data, 4) != 0) {
      $str .= $data;
    }
    close CLIPBOARD;
  }

  $_[0]->tt_write($_[0]->locale_encode($str));
  ()
}

sub on_user_command {
  my ($self, $cmd) = @_;

  if ($cmd eq "x11-clipboard:paste") {
    $self->paste;
  }
  ()
}

